apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: v2v-conversion
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - patch
      - get
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - '*'
