apiVersion: v1
kind: Pod
metadata:
  name: v2v-conversion
spec:
  serviceAccountName: v2v-conversion
  containers:
    - name: kubevirt-v2v-conversion
      image: 'quay.io/nyoxi/kubevirt-v2v-conversion:1.12.1-1-gf665c0a'
      securityContext:
        privileged: true
      volumeMounts:
        - name: configuration
          mountPath: /data/input
        - name: kvm
          mountPath: /dev/kvm
        - name: a
          mountPath: /data/vm/disk1
        - name: b
          mountPath: /data/vm/disk2
        - name: v2v-conversion-temp
          mountPath: /var/tmp
        - name: vddk-pvc
          mountPath: /opt/vmware-vix-disklib-distrib
  volumes:
    - name: configuration
      secret:
        secretName: v2v-conversion
    - name: kvm
      hostPath:
        path: /dev/kvm
    - name: a
      persistentVolumeClaim:
        claimName: a-h8ht5
    - name: b
      persistentVolumeClaim:
        claimName: b-wsjnk
    - name: v2v-conversion-temp
      persistentVolumeClaim:
        claimName: v2v-conversion-temp
    - name: vddk-pvc
      persistentVolumeClaim:
        claimName: vddk-pvc
  restartPolicy: Never
