apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: v2v-vmware
rules:
  - apiGroups:
      - ''
    attributeRestrictions: null
    resources:
      - configmaps
      - endpoints
      - events
      - persistentvolumeclaims
      - pods
      - secrets
      - services
    verbs:
      - '*'
  - apiGroups:
      - ''
    attributeRestrictions: null
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - apps
    attributeRestrictions: null
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    attributeRestrictions: null
    resources:
      - servicemonitors
    verbs:
      - create
      - get
  - apiGroups:
      - kubevirt.io
    attributeRestrictions: null
    resources:
      - '*'
    verbs:
      - '*'
